### ISSUE TITLE
Issue with running npm install sn-filter-pane

### ISSUE THREAD

**Issue by leesmith084** [qlik-oss/sn-filter-pane#12]
HI there, have stumbled upon this new filter panel and appreciate it is in Experimental mode, but i have tried to install into my React project that currently utilises nebula and stardust. but whilst trying to install the sn-filter-pane i get an error as attached...
![Screenshot 2022-09-15 at 16 49 22](https://user-images.githubusercontent.com/95697734/190616066-d763df00-5337-42a2-9390-21faf0b0ea56.png)

this is going to be a great feature as we have been missing the filter panel since moving over to nebula, did try to build our own with little success.

**Comment by johanlahti** [comment]
Hi @leesmith084! Thanks for your input. Indeed it is in experimental mode, and the code is "a bit" hacky right now. I would not recommend trying to build upon what we have currently as it is still formalising and changing rapidly. In the coming months we will probably have something more solid to build upon.

I don't know if it helps in your case, but there is already a Listbox in Nebula.js which may satisfy your requirements. You can look at this example: https://github.com/qlik-oss/nebula.js/tree/master/examples/dev-mashup After all, a Filter pane is just a container for Listboxes.

**Comment by leesmith084** [comment]
> 

Superb, @johanlahti - Nebula is all fairly new to me, so am still finding my feet a bit with it. so i will check out the attached link for the listbox component :). thank you. and look forward to seeing the filterpane grow over the coming months. thank you. happy to be a tester if you need any external testing / support as this grows.
