### ISSUE TITLE
react as peerDependency

### ISSUE THREAD

**Issue by DanielS-Qlik** [qlik-oss/sn-filter-pane#14]
While moving react to the peerDependencies array in package.json, it gives an console error when running "npm start".
For now the workaround is to run "npm link:nebula" and follow the instructions there.

**Comment by johanlahti** [comment]
Will close this since other pkgs also do it this way. For the one interested in digging further, it should be possible to look into the build scripts of Nebula. E.g. if we can e.g. add a `resolve.alias` (webpack) and point it to a specific react path. Or other ideas…
